name: Build Release
description: Builds the release files, makes it very easy for me because im a bum.
author: kartfr

inputs:
  version:
    required: true
    description: "version of release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "latest"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build EXE
        run: |
          pyinstaller main.spec
        
