name: Build Release

permissions:
    contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version of release"
        
      body:
        type: string
        required: true
        description: "Release body"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build EXE
        run: pyinstaller main.spec
      - name: Move EXE To Current Directory
        run: mv "dist/Animation Reuploader.exe" .
      - name: Create Version File
        run: echo ${{ github.event.inputs.version }} > VERSION.txt 
      - name: Zip The Files
        run: zip -r AnimationReuploader.zip LICENSE.txt VERSION.txt "Animation Reuploader.exe"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.body }}
          files: AnimationReuploader.zip
        